### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by Charles-9802** [Droliven/MSRGCN#1]
您好作者，请问放出的代码的模型是不是和论文中的模型不是完全一样的呀，例如图卷积的层数，下采样上采样的层数，谢谢回答

**Comment by Droliven** [comment]
您好，刚看到提问，是否可以提供邮箱，方便我们详细讨论具体细节。

**Comment by Droliven** [comment]
下面这四张图是正文的图2，补充材料的表9，第4个尺度下的图卷积模块（ "D3&A3"合起来一共有 6 个 residual-GCN），以及第一个尺度对应的下采样层（Downsampling 0有2层图卷积），你可以再核查一下。更多问题欢迎提问。

The following four pictures are Fig. 2 in the main paper, Tab. 9 in the supp, the code of the GCNs in the 4th scale "D3&A3" with 6 residual-GCNs, and the code of "Downsampling 0" with 2 GCLs respectively. You can check it. More questions are welcome.

![2](https://user-images.githubusercontent.com/37187316/137245469-f251dec7-fd76-4647-97f9-36d7f091a7a7.png)

![3](https://user-images.githubusercontent.com/37187316/137245497-fb90e76b-cddf-470b-b46d-f7804f4dc219.png)

![1](https://user-images.githubusercontent.com/37187316/137245525-79753aab-2865-46b4-bba6-19fab865e51d.png)

![4](https://user-images.githubusercontent.com/37187316/137245536-6443f6b0-eae7-4c63-a064-4361c136abc3.png)

**Comment by Charles-9802** [comment]
非常感谢您的回答！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Droliven ***@***.***&gt;
发送时间: 2021年10月14日 11:22
收件人: Droliven/MSRGCN ***@***.***&gt;
抄送: BJTU_Xu ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Droliven/MSRGCN] 模型 (#1)





 
下面这四张图是正文的图2，补充材料的表9，第3个尺度下的图卷积模块（ "D3&amp;A3"合起来一共有 6 个 residual-GCN），以及第一个尺度对应的下采样层（Downsampling 0有2层图卷积），你可以再核查一下。更多问题欢迎提问。
 
The following four pictures are Fig. 2 in the main paper, Tab. 9 in the supp, the code of the GCNs in the 3rd scale "D3&amp;A3" with 6 residual-GCNs, and the code of "Downsampling 0" with 2 GCLs respectively. You can check it. More questions are welcome.
 

 

 

 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
