### ISSUE TITLE
Wrong parameter name in README.md

### ISSUE THREAD

**Issue by eshanvaid** [Droliven/MSRGCN#2]
In Evaluate and visualize results section of README.md, 
python main.py **--expname**=h36m --is_load=1 --model_path=ckpt/pretrained/h36m_in10out25dctn35_best_epoch82_err57.9256.pth --output_n=25 --dct_n=35 --test_manner=all

The parameter name is --expaname, but in main.py, the parameter name is actually --exp_name.

**Comment by Droliven** [comment]
Problem fixed，thank you.
