### ISSUE TITLE
H3.6M dataset may be unavailable

### ISSUE THREAD

**Issue by Droliven** [Droliven/MSRGCN#3]
The H3.6M DATASET preprocessed by someone (earlier researchers) used in this paper is no longer available or recommended by researchers in this field, it is strongly recommend to conduct experiments based on the OFFICAL DATASET at http://vision.imar.ro/human3.6m/description.php, please refer to https://github.com/facebookresearch/VideoPose3D/blob/main/DATASETS.md  for relevant pre-processing codes.

**Comment by zhangjinrong731** [comment]
请问是处理后的数据在MSRGCN文件夹的存放路径该如何设置？需要在哪个文件中修改相关参数?

**Comment by Droliven** [comment]
Line 133， 135 of MSRGCN/configs/config.py
