### ISSUE TITLE
Results on AMASS

### ISSUE THREAD

**Issue by GDam90** [Droliven/MSRGCN#5]
Hi, thank you for sharing the implementation of your interesting work.
I want to compare your method with others on [AMASS](https://amass.is.tue.mpg.de/) dataset.
Have you already tried this experiment? If yes, I would ask you to share the results kindly; otherwise, I would like to know if you have any suggestions to perform a fair comparison, possibly showing what I should change in the config file (Index2212/127/74, dim_repeat...).

Thank you.

**Comment by Droliven** [comment]
We did not run experiments on AMASS, if you want to do that, you may need to do multiscale joints grouping like our designs of H3.6M and CMU Mocap Dataset (you could find them in the Fig 1 of Main Paper and Fig 1 of Supp).
