### ISSUE TITLE
Performance of different actions.

### ISSUE THREAD

**Issue by Xuehao-Gao** [Droliven/MSRGCN#6]
Dear author,
    There are no evaluation performances of different actions or milliseconds prediction were output in the test.  I want to kown how to print these performance results (Table 1/2). 
Many Thanks!

**Comment by Droliven** [comment]
As shown in the following fig, you could print "total_loss" or visualize the summary file.

![屏幕截图 2022-02-24 105559](https://user-images.githubusercontent.com/37187316/155449042-dd29464f-7cbd-4c7f-aa76-02a756aa3056.png)
