### ISSUE TITLE
数据处理问题

### ISSUE THREAD

**Issue by zhangjinrong731** [Droliven/MSRGCN#7]
您好，没有看懂您对于h36m和cmu两个数据集的处理方法，请问这两个路径分别存放的东西是什么？是在这里讲训练集和测试集传入模型的吗？
![image](https://user-images.githubusercontent.com/49579978/164591722-56d0b5b6-fefa-47ed-b074-22ea248aa413.png)

**Comment by Droliven** [comment]
Please refer to the instructions in README.md

![image](https://user-images.githubusercontent.com/37187316/164613412-2513f1b0-4e61-48da-94a7-bf189a6367b7.png)

**Comment by zhangjinrong731** [comment]
请问论文中的实验结果是将epoch设置为5000后得到的结果吗？您在h36m上完成一次训练需要花多久呢？
![image](https://user-images.githubusercontent.com/49579978/164675108-7b7d89ec-690b-4cd7-880d-3e22467ac495.png)

**Comment by Droliven** [comment]
建议你训练过程中看 tensorboard 的 loss 曲线，曲线平稳不降即可停止训练，模型中间结果 checkpoints 都会保存的。
