### ISSUE TITLE
关于MSRGCN在h36m数据集上的复现问题

### ISSUE THREAD

**Issue by zhangjinrong731** [Droliven/MSRGCN#8]
您好，采用您提供的源码在h36m数据集上输入10帧预测25帧，最好的平均误差会在59mm左右，达不到论文中的57，请问在训练过程中有什么要注意的地方吗？十分感谢！

**Comment by Droliven** [comment]
(1)注意检查配置是否一致；（2）实验跑5次计算均值方差
