### ISSUE TITLE
MemoryError: Unable to allocate 4.55 GiB for an array with shape (35, 17432064)

### ISSUE THREAD

**Issue by heduo-star** [Droliven/MSRGCN#9]
@[Droliven](https://github.com/Droliven/MSRGCN/commits?author=Droliven)
Dear author：
I would like to know how big the device memory you used, mine is 16G, once I run **python main.py --exp_name=h36m --is_train=1 --output_n=25 --dct_n=35 --test_manner=all**, the computer freezes up.

**Comment by Droliven** [comment]
The Memory of my used mechine is 32G. You could also carry out this part of code online in the dataloader.__get_item__().
